name: easy_oauth
description: Another Flutter OAuth package for simplifying OAuth operations
version: 1.0.0
authors: 
  - Joe Birch <hitherejoebirch@googlemail.com>
  - Kevin A. Riedl <k.riedl@codeing.io>
  - DeJay <contact@dejaydev.com>
homepage: https://dejay.dev

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  flutter_webview_plugin: ^0.3.7

flutter:
