name: flutter_oauth
description: A flutter oauth package for performing oauth operations
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+13
  flutter_webview_plugin: ^0.3.0+2


flutter:
